export const StockAction = {
    SET_SYMBOL: 'SET_SYMBOL',
    SET_ALL_STOCKS: 'SET_ALL_STOCKS',
    SET_LAST_UPDATED_DATE: 'SET_LAST_UPDATED_DATE',
    GET_LAST_UPDATED_DATE: 'GET_LAST_UPDATED_DATE',
    GET_LAST_UPDATED_DATE_SUCCESS: 'GET_LAST_UPDATED_DATE_SUCCESS',
    GET_MARKET_TRADING_STATISTIC: 'GET_MARKET_TRADING_STATISTIC',
    GET_MARKET_TRADING_STATISTIC_SUCCESS: 'GET_MARKET_TRADING_STATISTIC_SUCCESS',
    GET_HISTORICAL_QUOTES: 'GET_HISTORICAL_QUOTES'
}

export const ModalAction = {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL'
}