export const StockAction = {
    SET_SYMBOL: 'SET_SYMBOL',
    SET_ALL_STOCKS: 'SET_ALL_STOCKS',
    SET_LAST_UPDATED_DATE: 'SET_LAST_UPDATED_DATE',
    GET_LAST_UPDATED_DATE_REQUEST: 'GET_LAST_UPDATED_DATE_REQUEST',
    GET_LAST_UPDATED_DATE_REQUEST_SUCCEESS: 'GET_LAST_UPDATED_DATE_REQUEST_SUCCEESS',
    GET_MARKET_TRADING_STATISTIC_REQUEST: 'GET_MARKET_TRADING_STATISTIC_REQUEST',
    GET_MARKET_TRADING_STATISTIC_REQUEST_SUCCEESS: 'GET_MARKET_TRADING_STATISTIC_REQUEST_SUCCEESS',
}